const technologyCatalog = {
  html: { name: 'HTML5', category: 'Estrutura web', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg', summary: 'A linguagem de marcação que organiza o conteúdo e a estrutura de páginas na web.', description: 'HTML define a estrutura semântica de textos, links, imagens, formulários e outros elementos que compõem uma página.', purpose: 'Construir páginas organizadas, acessíveis e preparadas para receber estilo e interatividade.', official: 'https://developer.mozilla.org/pt-BR/docs/Web/HTML' },
  css: { name: 'CSS3', category: 'Estilo web', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg', summary: 'A linguagem de estilos usada para definir apresentação, layout e responsividade na web.', description: 'CSS controla cores, tipografia, espaçamento, grades, transições e o comportamento visual de interfaces.', purpose: 'Criar páginas responsivas, consistentes e claras em diferentes tamanhos de tela.', official: 'https://developer.mozilla.org/pt-BR/docs/Web/CSS' },
  java: { name: 'Java', category: 'Linguagem', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg', summary: 'Uma linguagem de programação de propósito geral, conhecida por sua portabilidade.', description: 'Java é utilizada para desenvolver aplicações e exercitar conceitos como orientação a objetos, classes e estruturas de dados.', purpose: 'Fortalecer lógica de programação e fundamentos de desenvolvimento de software.', official: 'https://dev.java/' },
  python: { name: 'Python', category: 'Linguagem', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg', summary: 'Uma linguagem de programação versátil, com sintaxe legível e ampla aplicação.', description: 'Python pode ser utilizada para automação, dados, scripts e aplicações, tornando-se útil para explorar diferentes áreas.', purpose: 'Praticar lógica, automação e resolução de problemas com código.', official: 'https://www.python.org/' },
  php: { name: 'PHP', category: 'Web backend', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg', summary: 'Uma linguagem voltada especialmente ao desenvolvimento de aplicações para web.', description: 'PHP é usada no lado do servidor para trabalhar com regras de negócio, páginas dinâmicas e integração com bancos de dados.', purpose: 'Entender a construção de funcionalidades web além da camada visual.', official: 'https://www.php.net/' },
  dart: { name: 'Dart', category: 'Linguagem', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dart/dart-original.svg', summary: 'Uma linguagem moderna usada principalmente no ecossistema Flutter.', description: 'Dart oferece recursos de linguagem para organizar aplicações e criar experiências em mais de uma plataforma.', purpose: 'Desenvolver a base de programação usada em projetos com Flutter.', official: 'https://dart.dev/' },
  flutter: { name: 'Flutter', category: 'Framework', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/flutter/flutter-original.svg', summary: 'Um framework para criar aplicações para múltiplas plataformas a partir de uma base de código.', description: 'Flutter utiliza widgets para compor interfaces e é acompanhado pela linguagem Dart no desenvolvimento de aplicações.', purpose: 'Explorar a construção de interfaces e aplicativos multiplataforma.', official: 'https://flutter.dev/' },
  laravel: { name: 'Laravel', category: 'Framework', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/laravel/laravel-original.svg', summary: 'Um framework para desenvolvimento de aplicações web com PHP.', description: 'Laravel reúne recursos para organizar rotas, dados, regras de negócio e outras partes comuns de uma aplicação web.', purpose: 'Conhecer padrões de organização para projetos web desenvolvidos com PHP.', official: 'https://laravel.com/' },
  nodejs: { name: 'Node.js', category: 'Runtime', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg', summary: 'Um ambiente de execução que permite usar JavaScript fora do navegador.', description: 'Node.js é usado para criar ferramentas, serviços e aplicações que rodam do lado do servidor.', purpose: 'Ampliar o repertório de desenvolvimento de aplicações web e scripts.', official: 'https://nodejs.org/' },
  mysql: { name: 'MySQL', category: 'Banco de dados', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg', summary: 'Um sistema de gerenciamento de banco de dados relacional.', description: 'MySQL permite organizar dados em tabelas e realizar consultas com SQL em aplicações e projetos de estudo.', purpose: 'Praticar modelagem, armazenamento e consulta de informações.', official: 'https://www.mysql.com/' },
  bootstrap: { name: 'Bootstrap', category: 'Biblioteca CSS', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-original.svg', summary: 'Uma biblioteca de componentes e estilos para interfaces web.', description: 'Bootstrap oferece estruturas, utilitários e componentes prontos para apoiar a criação de páginas responsivas.', purpose: 'Explorar padrões de interface e acelerar protótipos web.', official: 'https://getbootstrap.com/' },
  git: { name: 'Git', category: 'Versionamento', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg', summary: 'Um sistema distribuído de controle de versão para acompanhar mudanças em projetos.', description: 'Git registra versões de arquivos e permite organizar a evolução do código durante o desenvolvimento.', purpose: 'Manter histórico de alterações e trabalhar com boas práticas de versionamento.', official: 'https://git-scm.com/' },
  github: { name: 'GitHub', category: 'Colaboração', logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg', summary: 'Uma plataforma para hospedar repositórios, compartilhar código e colaborar em projetos.', description: 'GitHub integra recursos de repositórios Git, documentação e publicação de projetos na web.', purpose: 'Publicar estudos, acompanhar projetos e construir presença técnica.', official: 'https://github.com/' }
};

const requestedTechnology = new URLSearchParams(window.location.search).get('id');
const technology = technologyCatalog[requestedTechnology] || technologyCatalog.html;
document.title = `${technology.name} — Miguel Marques Borges`;
document.getElementById('detail-category').textContent = technology.category;
document.getElementById('detail-name').textContent = technology.name;
document.getElementById('detail-summary').textContent = technology.summary;
document.getElementById('detail-description').textContent = technology.description;
document.getElementById('detail-purpose').textContent = technology.purpose;
document.getElementById('detail-logo').style.setProperty('--logo', `url('${technology.logo}')`);
const officialLink = document.getElementById('detail-official');
officialLink.href = technology.official;
officialLink.target = '_blank';
officialLink.rel = 'noreferrer';
